### ISSUE TITLE
Burrow clone creates symlink when clone is used within gopath

### ISSUE THREAD

**Issue by martin31821** [EmbeddedEnterprises/burrow#2] opened 2018-04-29 12:42 UTC
Burrow should catch clones within the gopath.

**Comment by fin-ger** [comment] 2018-06-05 12:48
This is not a bug. This is intended behavior. Have a look in the manual which states:

```
clone                  Clone a git repository into your GOPATH and create a symbolic link in your current location.
```

However, we can think about changing the behavior of `clone` to also work inside the GOPATH. If this is desired, please add the `enhancement` label. For now I will close this issue.

**Comment by fin-ger** [comment] 2018-06-05 16:54
Decided to add as feature.

**Closed as completed** 2018-06-05 17:00 UTC
Labels: enhancement
